{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- with $component.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name "component" $component) }}
  labels:
    {{ include "commons.labels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name "component" $component) | nindent 4 }}
spec:
  replicas: {{ default 1 .replicas }}
  {{- with .strategy }}
  strategy:
    type: {{ default "RollingUpdate" .type }}
  {{- end }}
  selector:
    matchLabels:
      {{ include "commons.selectorLabels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name "component" $component) | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "commons.selectorLabels" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name "component" $component) | nindent 8 }}
        {{- range $index, $volume := .volumes }}
          {{- with $volume.configMap }}
            {{- with $volume.configMap.data }}
        checksum/{{ default $index $volume.name }}: {{ printf "%v" $volume.configMap.data | sha256sum | trunc 63 }}
            {{- end }}
          {{- end }}
        {{- end }}
    spec:
      {{- if $.Values.global.rbac.enabled }}
      serviceAccountName: {{ $.Values.global.rbac.serviceAccountName }}
      automountServiceAccountToken: true
      {{- end }}

      {{ include "containers.securityContext" (dict "global" $.Values.global "securityContext" .securityContext) | nindent 6 }}

      {{- with .hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}
      {{- with .initContainers }}
      initContainers:
        {{- range . }}
        - name: {{ .name | default $component.name }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .image.repository }}:{{ .image.tag | default "latest"  }}
          {{- with .command }}
          command:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- include "containers.envs" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "env" .env) | nindent 10 }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ default $component.name .name }}
          image: {{ .image.repository }}:{{ .image.tag | default "latest" }}
          {{- with .command }}
          command:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- include "containers.envs" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "env" .env) | nindent 10 }}

          {{- with .lifecycle }}
          lifecycle:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .volumeMounts }}
          volumeMounts:
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
          {{- end }}
          
          {{- if or .additionalsPorts  (and $component.service $component.service.ports) }}
          ports:
            {{- range $component.service.ports }}
            - name: {{ .name }}
              containerPort: {{ default .port .targetPort }}
              protocol: {{ default "TCP" .protocol }}
              {{- with .hostPort }}
              hostPort: {{ . }}
              {{- end }}
            {{- end }}
            {{- range .additionalsPorts }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ default "TCP" .protocol }}
              {{- with .hostPort }}
              hostPort: {{ . }}
              {{- end }}
            {{- end }}
          {{- end }}
          
          {{ include "containers.probes" . | nindent 10 }}

          {{- with .resources }}
          resources:
             {{- toYaml . | nindent 12 }}
          {{- end }}
        {{ include "containers.sidecars" (dict "component" $component "Values" $.Values) | nindent 8 }}
      {{- with .volumes }}
      volumes:
        {{- range . }}
        {{- if .configMap }}
        - name: {{ .name }}
          configMap:
            {{- if .configMap.useExisting }}
            name: {{ include "commons.getValue" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "value" .configMap.name) }}
            {{- else }}
            name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default .name .configMap.name) "component" $component) }}
            {{- end }}
            {{- with .configMap.defaultMode }}
            defaultMode: {{ . }}
            {{- end }}
            {{- with .configMap.readOnly }}
            readOnly: {{ . }}
            {{- end }}
        {{- else if .pvc }}
        - name: {{ .name }}
          persistentVolumeClaim:
            {{- if .pvc.useExisting }}
            claimName: {{ include "commons.getValue" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "component" $component "value" .pvc.name) }}
            {{- else }}
            claimName: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" (default .name .pvc.name) "component" $component) }}
            {{- end }}
            {{- with .pvc.readOnly }}
            readOnly: {{ . }}
            {{- end }}
        {{- else }}
        - {{ toYaml . | nindent 10 | trim }}
          {{- end }}
        {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}