{{- $components := include "commons.withAddons" . | fromYamlArray }}
{{- range $components }}
{{- $component := . }}
{{- range $component.cronjobs }}
{{- if .runOnStartup }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "commons.fullname" (dict "Chart" $.Chart "Values" $.Values "Release" $.Release "name" .name "component" $component) }}
spec:
  template:
    spec:
      restartPolicy: {{ default "Never" .restartPolicy }}

      {{- with .nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .containers }}
      containers:
        {{- range . }}
        - name: {{ default $component.name .name }}
          image: {{ .image.repository }}:{{ .image.tag | default "latest" }}
          {{- with .command }}
          command:
            {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .args }}
          args:
            {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 16 }}
          {{- end }}
          {{- with .lifecycle }}
          lifecycle:
          {{- toYaml . | nindent 16 }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
          {{- end }}
          

          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 16 }}
          {{- end }}
        {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}