apiVersion: v2
name: nextcloud
description: Nextcloud
type: application
version: 0.4.0
appVersion: "32.0.0"
keywords:
  - nextcloud
dependencies:
- name: redis
  version: 24.0.0
  repository: https://charts.bitnami.com/bitnami
